### ISSUE TITLE
Generierung von Einzel-PDF

### ISSUE THREAD

**Issue by michkoll** [michkoll/latex-template-cheatsheet#6]
Es sollte automatisch möglich sein die Cheatsheets einzeln zu erstellen. Dazu eventuell kleines Skript schreiben, was die Erstellung der EinzelPDFs ermöglicht (Shell, Makefile, o.ä.)

**Comment by anionDev** [comment]
Soll es für jede .tex-datei ein einzelnes Skript geben, das die jeweilige .tex-datei kompiliert oder soll es ein Skript geben, das ein .tex-dateinamen als Argument entgegen nimmt?

**Comment by michkoll** [comment]
Ja gute Frage, weiß es auch noch nicht genau. War eher so ein Reminder für mich ;)
Ich hätte gerne, dass man auf möglichst einfache Weise entweder ein GesamtPDF oder EinzelPDFs  machen kann. Hab mich aber noch nicht näher damit beschäftigt was der beste Weg wäre. Bin für Vorschläge offen.

**Comment by m4ttb1ss** [comment]
Ich denke am sinnvollsten wäre es ein Script zu haben was sowohl die Gesamt-pdf als auch die einzel-pdfs erstellt

**Comment by anionDev** [comment]
in pullrequest #9  hab ich mal ein script dafür erstellt. bei fragen und anmerkungen immer her damit.
